### ISSUE TITLE
Multicast routing between two virtual vlan interfaces

### ISSUE THREAD

**Issue by juddmeinders** [troglobit/smcroute#142] opened 2019-12-02 18:49 UTC
I've been searching for someone with a similar setup as me, but I haven't been able to find so I'm left here to ask the question.

I have a linux machine that has a single physical interface that I would like to route multicast on between two virtual interfaces that have that same physical parent.  The virtual interfaces exist in order to separate the between 3 vlans. (The switch tags with 802.3Q for wolf_vlan and dev_vlan)

When I send multicast traffic from wolf_vlan (192.168.2.110) to 238.198.16.6, I would expect that multicast traffic to be routed back out the dev_vlan virtual interface.  But it ends up coming out the enp1s0f0 interface, which is the physical parent of both virtual interfaces.  Have I configured something incorrectly?  Configuration outputs below.

**ip -d link show**:
2: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:25:90:65:c7:7a brd ff:ff:ff:ff:ff:ff promiscuity 0 addrgenmode none
491: wolf_vlan@enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:25:90:65:c7:7a brd ff:ff:ff:ff:ff:ff promiscuity 0
    vlan protocol 802.1Q id 8 <REORDER_HDR> addrgenmode none
492: dev_vlan@enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:25:90:65:c7:7a brd ff:ff:ff:ff:ff:ff promiscuity 0
    vlan protocol 802.1Q id 12 <REORDER_HDR> addrgenmode none

**ip mroute**:
(192.168.2.110, 238.198.16.6)    Iif: wolf_vlan  Oifs: dev_vlan
(192.168.3.94, 238.198.16.6)     Iif: dev_vlan   Oifs: wolf_vlan
(192.168.3.94, 224.2.100.100)    Iif: dev_vlan   Oifs: wolf_vlan
(192.168.2.109, 239.198.16.62)   Iif: wolf_vlan
(192.168.2.109, 239.198.16.88)   Iif: wolf_vlan
(192.168.2.109, 238.198.16.3)    Iif: wolf_vlan
(192.168.3.94, 239.255.255.250)  Iif: dev_vlan
(192.168.2.110, 239.255.255.250) Iif: wolf_vlan
(192.168.2.113, 239.255.255.250) Iif: wolf_vlan
(192.168.2.111, 239.255.255.250) Iif: wolf_vlan
(192.168.2.112, 239.255.255.250) Iif: wolf_vlan

**cat smcroute.conf**:
phyint wolf_vlan enable
phyint dev_vlan enable

mgroup from wolf_vlan group 238.198.16.6
mgroup from wolf_vlan group 238.198.16.6 source 192.168.2.110
mroute from wolf_vlan group 238.198.16.6 source 192.168.2.110 to dev_vlan
mgroup from dev_vlan group 238.198.16.6
mgroup from dev_vlan group 238.198.16.6 source 192.168.3.94
mroute from dev_vlan group 238.198.16.6 source 192.168.3.94 to wolf_vlan
mgroup from dev_vlan group 224.2.100.100
mgroup from dev_vlan group 224.2.100.100 source 192.168.3.94
mroute from dev_vlan group 224.2.100.100 source 192.168.3.94 to wolf_vlan

**Comment by juddmeinders** [comment] 2019-12-02 19:57
Oh, using version 2.4.4 and here is my what my proc looks like:

**cat /proc/net/ip_mr_vif**:
Interface      BytesIn  PktsIn  BytesOut PktsOut Flags Local    Remote
 0 wolf_vlan  27245399   84921         0       0 00008 000001EB 00000000
 1 dev_vlan       7794      42         0       0 00008 000001EC 00000000


**cat /proc/net/ip_mr_cache**:
Group    Origin   Iif     Pkts    Bytes    Wrong Oifs
0610C6EE 6E02A8C0 0        630    80640        0  1:1
0610C6EE 5E03A8C0 1          0        0        0  0:1
646402E0 5E03A8C0 1          0        0        0  0:1
3E10C6EF 6D02A8C0 0      75160 27914091        0
5810C6EF 6D02A8C0 0      14139   966983        0
0310C6EE 6D02A8C0 0        767   142623        0
FAFFFFEF 5E03A8C0 1         42     7794        0
FAFFFFEF 6E02A8C0 0         12     1980        0
FAFFFFEF 7102A8C0 0         12     1980        0
FAFFFFEF 6F02A8C0 0         12     1980        0
FAFFFFEF 7002A8C0 0         12     1980        0

**Comment by troglobit** [comment] 2019-12-02 21:25
Hi, I think this is the same root cause as reported in #107, which seems to be a bug somewhere in the kernel, multicast routing between VLAN interfaces on the same base interface does not work properly.

Since it's not a burning issue at $DAYJOB atm, debugging this is unfortunately on a very low-priority for me, but that doesn't mean someone else can step up and help out.

**Comment by juddmeinders** [comment] 2019-12-03 21:51
Thanks for the reference.  I agree this is the same root. If this becomes a necessity at my current application, I will push for funding to get this figured out.  Otherwise maybe someone else will have the time.

**Comment by juddmeinders** [comment] 2019-12-04 18:23
Just for fun, I tried my same setup on a different machine that had two separate physical nics and I have the same results.  I've checked to make sure my linux config items match the requirements on Linux Requirements section and they do.  I also have my iptables forward, input, and output chains set to ACCEPT as default policy while I'm troubleshooting.   ip_forward is set to 1 also.

**Comment by troglobit** [comment] 2021-07-27 19:53
We now have an automated test suite for SMCRoute with a VLAN test that matches issue #161.  The only major difference from your setup is that you have the same multicast group with different source ingressing on different interfaces.  That has been tricky to get right with (*,G) routes, but your setup uses proper (S,G) routes, so it shouldn't be a problem.

This is the latest run from the SMCRoute master branch.  Check the link to see OS details of the Azure runner.

https://github.com/troglobit/smcroute/actions/runs/1072472846

Since it's working fine, I'm concluding this must have been caused by a Linux kernel regression, i.e. not a problem with SMCRoute. Closing.

**Closed by troglobit** 2021-07-27 19:53 UTC
Labels: help-wanted
