### ISSUE TITLE
Mroutes not loading correctly from conf in a multiple vlan and physical interface scenario. 

### ISSUE THREAD

**Issue by yordanomp** [troglobit/smcroute#161] opened 2021-06-14 21:37 UTC
I had a scenario similar to #142 were I had to 2 vlans (vlan100, vlan101) over one interface (enp1s0f1) routing multicast from vlan100 to vlan101. This was working ok for 100's of multicast using (*,G) routes in `smcroute.conf`.

The problem comes when I try to share multicast from a new vlan (vlan102) in other physical interface (enp1s0f0) to one of the others (vlan100, vlan101). In this case `smcrouted` reads the config and raises an error for the (*,G) route line or doesn't do anything. The thing is, it works when I add the new route via `smcroutectl` as I will show in the example below. 

This is a stripped configuration of what I'm doing with a diagram:

```
                                                   
+---------------------+                                                                                  
|                     |    enp1s0f1 - VLAN 100     
|                     <---------------------->     
|                     |                                                     
|                     |    enp1s0f1 - VLAN 101     
|      SMCROUTE       <---------------------->     
|                     |                                                       
|                     |    enp1s0f0 - VLAN 102     
|                     <---------------------->     
|                     |                                                                                
+---------------------+                            
                                                                                                
                                                   
```

```
phyint vlan100 enable
phyint vlan101 enable
phyint vlan102 enable
mgroup from vlan100 group 239.3.0.101
mroute from vlan100 group 239.3.0.101 to vlan101 vlan102

mgroup from vlan102 group 238.0.2.2
mgroup from vlan102 group 238.0.2.2 to vlan101 vlan100 

```

This is an output of the `smcrouted` when I try to run it:

```
smcroute[4672]: /etc/smcroute.conf:18: Read line: 'mgroup from vlan102 group 238.0.2.2
'
smcroute[4672]: /etc/smcroute.conf:19: Read line: 'mgroup from vlan102 group 238.0.2.2 to vlan101 vlan100
'
smcroute[4672]: failed join (*,238.0.2.2), already member

```

If I comment out the join because I'm receiving the multicast statically, this is what I get:
```
smcroute[4736]: /etc/smcroute.conf:18: Read line: '#mgroup from vlan102 group 238.0.2.2
'
smcroute[4736]: /etc/smcroute.conf:19: Read line: 'mgroup from vlan102 group 238.0.2.2 to vlan101 vlan100
'
smcroute[4736]: /etc/smcroute.conf:20: Read line: '
.
.
smcroute[4736]: Multicast from 10.20.20.2, group 238.0.2.2, on vlan102 does not match any (*,G) rule
'
```

The route doesn't get installed without error as can also confirm with `smcroutectl show`:
```
ROUTE (S,G)                        INBOUND             PACKETS      BYTES  OUTBOUND
(*, 239.3.0.101)                   vlan100                   0          0  vlan101 vlan102
(10.20.20.2, 238.0.2.2)            vlan102              120860  162435840
(10.30.30.10, 239.3.0.101)         vlan100              107231  139681288  vlan101 vlan102
```

Insted, if I add the route via the command `smcroutectl add vlan102 238.0.2.2 vlan101 vlan100` it works ok as we can see in this output:
```
ROUTE (S,G)                        INBOUND             PACKETS      BYTES  OUTBOUND
(*, 238.0.2.2)                     vlan102                   0          0  vlan100 vlan101
(*, 239.3.0.101)                   vlan100                   0          0  vlan101 vlan102
(10.20.20.2, 238.0.2.2)            vlan102              240128  322732032  vlan100 vlan101
(10.30.30.10, 239.3.0.101)         vlan100             1170369 1524829512  vlan101 vlan102
```

**Context:**

* Version: **v2.4.4**
* Distro: **Ubuntu 20.04.2**
* Kernel: **5.4.0-74-generic x86_64**

**Comment by troglobit** [comment] 2021-06-15 08:29
Thank you for the excellent report.  It's quite possible your particular bug is fixed on master already.  If at all possible, it would be greatly appreciated if you could try that out.

On a personal note: I've been busy with many other projects for quite a while now, and it's about time I get back to working on SMCRoute, finalize the big `mroute.c` refactor (to fix TODO item n:o 1), and get the v2.5.0 release out.

**Comment by yordanomp** [comment] 2021-06-15 15:42
Sure. I'm trying at this moment with the master branch and the behavior is the same.

**Comment by troglobit** [comment] 2021-06-15 15:54
Awesome, thank you for taking the time to verify! <3

**Comment by yordanomp** [comment] 2021-06-17 18:58
Sure, thank you for this project. If you need me to test something just let me know.

**Comment by troglobit** [comment] 2021-07-10 13:47
Got back to this again and just noticed in your report:

```
mgroup from vlan100 group 239.3.0.101
mroute from vlan100 group 239.3.0.101 to vlan101 vlan102

mgroup from vlan102 group 238.0.2.2
mgroup from vlan102 group 238.0.2.2 to vlan101 vlan100 
```

The last line's supposed to be an `mroute` right, not `mgroup`?

**Comment by yordanomp** [comment] 2021-07-10 14:04
Yes, sorry for the typo, the last line is a `mroute`

**Comment by troglobit** [comment] 2021-07-10 14:19
No problem, just double checking :)

**Comment by troglobit** [comment] 2021-07-10 15:06
With a similar setup as you in [CORE](https://github.com/coreemu/core) I cannot reproduce.  I've set it up as follows using the iproute2 commands `ip link`, to create the VLAN interfaces on top of eth0 and eth1, and `ip addr` and `ip route` to set up layer-3.

      __________________         __________________________
     |                  |       |                          |
     |     vlan100      |       |      vlan100             |     ________________________
     |            \     |       |     /                    |    |                        |
     |             eth0 ========= eth0     vlan102 -- eth1 ====== eth0 -- vlan102        |
     |            /     |       |     \                    |    |________________________|
     |     vlan101      |       |      vlan101             |      End Device 2
     |__________________|       |__________________________|
           End Device 1                SMCRoute router

I used the exact same groups as you, only changing the last line to be `mroute`.  The IP address plan is slightly different though, I
used 10.0.$VID.n/24, but that shouldn't matter.  I get no errors or warnings from smcrouted (master branch).

I run Linux Mint 20.2, which is based on Ubuntu 20.04.

```sh
~$ uname -a 
Linux wbg 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by troglobit** [comment] 2021-07-27 19:46
Closing, this seems to work fine now on the latest master branch.  I've updated the VLAN test to match the case covered here, and it's all green as of https://github.com/troglobit/smcroute/actions/runs/1072472846

Check the link above to see OS details of the Azure runner.

**Closed by troglobit** 2021-07-27 19:46 UTC
