### ISSUE TITLE
20 group limit, 200 route limit

### ISSUE THREAD

**Issue by joflo5712** [troglobit/smcroute#18] opened 2015-08-13 23:53 UTC
I was wondering if you could please explain why SMCroute is limited to 20 groups and 200 routes.  My multicast network application requires a larger number of groups and static routes to be supported.

Is this due to a Linux kernel limitation?

Is it possible to scale SMCroute up to support more groups/routes with a code change?  

Can you suggest an alternative approach to allow for a greater number of groups/routes?

Thanks
Joseph Flores

**Comment by troglobit** [comment] 2015-08-14 10:31
Good question, let me investigate where this comes from.  Doesn't look like there's anything hard wired inside smcroute at least ...

Have you tried > 20 groups and > 200 routes?  If anything you'll run in to a limit of `MAXVIFS` in the kernel, but that is more about the maximum number of interfaces you can have -- 32 according to the kernel.

Investigating ...

**Comment by troglobit** [comment] 2015-08-14 10:57
OK, I can confirm that the maximum number of `mgroup` lines you can have, per inbound interface, is 20.  Don't know why this is atm, could be a per socket option we could change.  But you shouldn't really need that option, unless you have troublesome layer 2+ switches doing IGMP/MLD snooping on the inbound network.  The problem is that the smcroute socket would receive a copy of each multicast frame, so this isn't really a good use for the `mgroup` setting.  Guess I should document this ...

Howver, and probably more interesting for you, I also tried setting up 1000 `mroute` lines, without any problem.  So I guess that limit in the man page is an old one.  

I tested on Linux 3.19, Ubuntu 15.04.

Please let me know if this helps so we can close this issue.

**Comment by troglobit** [comment] 2015-08-20 14:39
Closing due to inactivity, please reopen if you have any further questions.

**Closed by troglobit** 2015-08-20 14:39 UTC
