### ISSUE TITLE
Over 20 Group Entries in smcroute.conf

### ISSUE THREAD

**Issue by sharbich** [troglobit/smcroute#33] opened 2016-03-29 23:42 UTC
When I create over 20 Entries in the smcroute.conf via

    phyint ppp0 enable ttl-threshold 26
    phyint lan-1.50 enable
    mgroup from ppp0 group 239.35.10.4
    mroute from ppp0 group 239.35.10.4 source 193.158.35.251 to lan-1.1 lan-1.50 wlan-1

The Transmitter for the Internet Site (ppp0), has over 100 Group's. The Performance for the Picture on the TV is verry slow.
All another multicast deamon on linux (pimd) are not running. The onlay works is the igmpproxy. But I need two, because I have I internal Plex Media Server, there send Multicast.
Unfortunately I can at the igmpproxy now one upstream Interface.
What can I do if I only two Transmitter for Multicast

**Comment by troglobit** [comment] 2016-03-30 02:17
Not sure I understand your question, is it a performance issue or a functional problem?

**Comment by sharbich** [comment] 2016-03-30 07:09
I receive more than 100 channels on my TV over IPTV Deutsche Telekom Entertain VDSL100. Each transmitter has a different set. In the first article for example `239.35.10.4`. I visit now about 100 items of the smcroute.conf. The Picture on the Television are distorted and remains.
The Question is both (Performance and Functional problem)

**Comment by troglobit** [comment] 2016-03-30 09:27
In our previous discussion in troglobit/pimd#74 I didn't realize the full scope of your problem, since I recommended you `smcroute`, but understanding the problem is half the solution I guess ...

Routing 100 simultaneous multicast groups would be quite demanding on any CPU based router. All `smcroute` does is to create multicast routes in the kernel, if that works (c.f. `ip mroute show`), then there is no functional problem (bug) with `smcroute`, but rather a performance issue with your router.  This is easy to verify by simply reducing the amount of routes to a handful, or even a couple.

Routing of multicast traffic is, like I've tried explaining before, quite different from routing unicast traffic. For a fully working setup, which does what I think I you want (automatically route only the channels you select on your TV), you need something more like `igmpproxy`.

**Comment by sharbich** [comment] 2016-03-30 14:29
When I like the igmpproxy i can't configure now one upstream Interface. I am looking for the Solution then configure more then one upstream Interface. That is not pimd, smcroute or mrouted. The next plan is, I am check the mcproxy.

**Comment by troglobit** [comment] 2016-03-30 15:30
OK, good luck. Meanwhile I'm closing this issue.

**Closed by troglobit** 2016-03-30 15:30 UTC
