### ISSUE TITLE
what is the problem with IPv6 multicast routing support (*, G)

### ISSUE THREAD

**Issue by JustHzheng** [troglobit/smcroute#121] opened 2019-03-21 02:55 UTC
Can IPv6 multicast routing be enabled (*, G) like IPV4

**Comment by troglobit** [comment] 2019-03-21 13:31
This is a duplicate of #31.  Support for IPv6 wildcard routes is still TODO.  I have not had any need for it myself yet (and have very little exposure to IPv6 in general) so anyone else can jump in and help out.

I'm closing this now, please use #31 for further discussions on this topic.

**Closed by troglobit** 2019-03-21 13:31 UTC
