### ISSUE TITLE
smcroute between two Centos7 Server over GRE

### ISSUE THREAD

**Issue by subwoofer17** [troglobit/smcroute#107] opened 2019-01-22 15:51 UTC
Hi,

i hope you can help me with my problem and i hope i am right here. I am new in github and smcroute and hope we can solve my problem together.

I have two up to date CentOS 7 Server und setup a GRE Tunnel between them. That works fine, i can transmit packets between the machines. Both Server have only one physical nic named "ens160" and a virtuel named "tun0" in my config.

And i would transfare the multicast vom Client1 -> in vlan1 -> to host1 -> oder GRE -> to host2 -> in vlan2

I can the the MC traffic with tcpdump arriving on tun0 on host2. So MC forwarding von host1 over GRE works fine. But the host don´t send out the MC traffic to vlan2.

smcroute host1

phyint ens160 enable ttl-threshold 3
phyint tun0 enable ttl-threshold 3
mgroup from ens160 group 225.3.2.1
mroute from ens160 group 225.3.2.1 to tun0

smcroute host2
phyint ens160 enable ttl-threshold 8
phyint tun0 enable ttl-threshold 8
mgroup from tun0 group 225.3.2.1
mroute from tun0 group 225.3.2.1 to ens160

But with "smcroutectl show routes" i can´t the packets

ROUTE (S,G)                        INBOUND             PACKETS      BYTES  OUTBOUND
(*, 225.3.2.1)                     tun0                      0          0  ens160

what can i do so thats working? Or is there a problem that the MC Packets are not realy inbount to tun0, because they leave the GRE tunnel at tun0.

I hope you can halp me

Regardes

Andre

**Comment by troglobit** [comment] 2019-01-23 05:18
Since you've set up a `ttl-threshold` for all your interfaces (this is an optional setting), your multicast data stream for group 225.3.2.1 must have a TTL value > 4 to be routed out from host1, and > 8 to be allowed to be routed in on host2, i.e. TTL > 100 to be allowed to be routed at both routers.   You say you can see the data stream on host2 with tcpdump, so what's the TTL of the inbound traffic on the tun0 interface?

**Comment by subwoofer17** [comment] 2019-01-23 11:16
Hi,

TTL on tun0 of the host2 is 15, i send it out by my MC Generator with 15. 

I think that the problem is the tun0 interface on host2, because it´s an output interface and no input. The GRE Tunnel end at this interface so the traffic goes out of the tunnel trough tun0. So in my opinion the smcroute checks only input in tun0. It is da little bit different as the server has two physical interfaces.

Any other idea?

**Comment by troglobit** [comment] 2019-01-23 20:01
I'm not sure what you mean by "because it´s an output interface and no input"?  A tunnel goes both ways ... also SMCRoute is a *static* multicast router, except for the (*,G) support, so iit doesn't do anything in particular about the input.

However, since you only have one physical interface (I totally overlooked that), I'll have to look into this in more detail to give you a better answer. The following is a HowTo I wrote for GRE + PIM-SM, which may provide some help. I may get some time this weekend to set something similar up withj GRE + SMCRoute, but until then: http://troglobit.com/2016/07/05/multicast-routing-with-pim-sm-over-gre/

**Comment by troglobit** [comment] 2019-01-24 19:41
Well, I get the same result as you do with a single physical interface. The kernel doesn't do any upcalls (IGMPMSG_NOCACHE) on the GRE interface on the other side of the tunnel, so no (S,G) multicast route is established. I even tested with `pimd` instead of SMCRoute and had the same result. So it's not a problem just with SMCRoute and GRE, it could be a kernel issue, or something that can be configured, e.g. using sysctl. 

I'll continue debugging this, but from the kernel side. Got some help from a colleague (author of `ply`)  today using `ply` to trace where in the kernel packets get stuck. From what we currently can see the encapsulated multicast frames don't even leave the GRE tunnel and hit the IP multicast code in the kernel. So it's a bit of a mystery at the moment ...

**Comment by subwoofer17** [comment] 2019-01-29 20:47
Sorry for delayed repsone, i am some days out of office. I hope you can find whats go wrong in the kernel with the packets.
It will be nice if you post your findings here and and i hope you can solve the problem.

Regardes

Andre

**Comment by johhnyh** [comment] 2019-04-15 05:27
Hi -- 

I am having the exact same problem and was very happy to see it reported! I also have tried both pimd as well as SMCroute. 

I don't believe it's traffic generation on each side, and multicast via static route from each GRE end point works, but does not get broadcast out the LAN interface.

Have you guys had any luck?

Thanks

**Comment by troglobit** [comment] 2019-04-15 06:51
I have not had a chance to look into this further, but from the initial investigation it seems to be a Linux kernel issue rather than a problem with SMCRoute.

**Comment by johhnyh** [comment] 2019-04-15 09:21
Thanks for the fast reply!

Before I dig into kernel regressions are you able to confirm this is a configuration that should work? If so, what distro have you seen it on? Ill go try something I know works first. 

Thanks!

**Comment by troglobit** [comment] 2019-04-15 09:27
I've never set up something like this until now.  It's a brilliant solution to a common problem and I don't see why it shouldn't be supported by the kernel. Like I said, I think this is a kernel issue and I'm pretty sure it's not distribution specific.

Also, I wouldn't be surprised if this has never been tried before, so it's likely not a regression in the kernel but rather missing functionality of an oversight.

**Comment by johhnyh** [comment] 2019-04-15 13:13
Thanks for the detail.

My real use case is actually simpler, but the "2 broadcast servers connected via a tunnel" is very appealing, and I was testing a hopeful/best case. 

What I'm actually trying to do and struggling is a subset of this ticket which is;

Single multicast client (duplex - rx+tx) on Host A connected to Host B via GRE which  is on the "multicast subnet" 

"multicast subnet" has a number of servers all broadcasting and receiving multicast (including from Host A via tunnel via Host B). There is a valid switch provided RP / PIM layer as well as functional layer2 IGMP joins, etc.

In your experience is this something seemingly possible? 

I can trigger traffic into host B but not having much luck with it then routing via the tunnel.


ip_mr_vif 

```
Interface      BytesIn  PktsIn  BytesOut PktsOut Flags Local    Remote
 0 eth0       11809979   14493    425180    2746 00000 3DC8A10A 00000000
 1 tun0              0       0         0       0 00000 01A8A8C0 FFA8A8C0
 2 pimreg       425180    2746         0       0 00004 3DC8A10A 00000000
```

**Comment by troglobit** [comment] 2019-04-15 14:41
Almost anything is possible with software. I don't fully understand your setup though, but to be able to run SMCRoute and PIM on the same server you must use different multicast routing tables or different network namespaces. 

I'm assuming you've verified the TTL of the multicast traffic you're attempting to route ...

**Comment by lubouski** [comment] 2019-05-03 10:26
@troglobit Greetings :) May be you could help me 🥇 

I'm facing similar issue with SMCROUTE.

My setup is two hosts. With vxlan overlay network between them. 

HOST1:
VXLAN interface configuration:
```
16: vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 1e:51:8d:49:f4:33 brd ff:ff:ff:ff:ff:ff
    inet 10.20.1.2/24 scope global vxlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::1c51:8dff:fe49:f433/64 scope link
       valid_lft forever preferred_lft forever
```
SMCROUTE config:
```
$ cat /etc/smcroute.conf
mgroup from ens192 group 225.1.2.3
mroute from ens192 group 225.1.2.3 to vxlan0
```
Also I added iptables rule that allow FORWARDING to vxlan0 interface. 
!!! And with this setup *SMCROUTE* works perfectly I can see Multicast traffic on *HOST2* in tcpdump on similar vxlan0 interface.

But on HOST2:
vxlan0 interface:
```
16: vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether b2:93:ae:86:bd:bd brd ff:ff:ff:ff:ff:ff
    inet 10.20.1.1/24 scope global vxlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::b093:aeff:fe86:bdbd/64 scope link
       valid_lft forever preferred_lft forever
```
I also have macvlan interface and want to sent Multicast traffic to that interface: 
```
4: macvlan@ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 12:5e:5f:cb:31:fb brd ff:ff:ff:ff:ff:ff
    inet 192.168.113.17/21 scope global macvlan
       valid_lft forever preferred_lft forever
    inet6 fe80::105e:5fff:fecb:31fb/64 scope link
       valid_lft forever preferred_lft forever
```
Here is SMCROUTE config:
```
cat /etc/smcroute.conf
#test
mgroup from vxlan0 225.1.2.3
mroute from vxlan0 225.1.2.3 to macvlan
```
!!! And when I'm sending multicast traffic from vxlan interface to macvlan it won't works, 
I tested problem is not with macvlan interface because in setup when I'm sending traffic from physical inteface ens192 to macvlan I could see traffic with tcpdump. 

P/S: Tested similar setup with GRE instead of VXLAN have the similar result, from ens interfaces to vxlan/gre SMCROUTE works perfectly, from vxlan/gre on other side to macvlan it won't 
TTL is fine, for test I use iperf (iperf -u -c 225.1.2.3 -T 10 -l 1376), routing is fine, and iptables rule added respectively.

**Comment by lubouski** [comment] 2019-05-11 07:38
@troglobit Hello, I figured out how to solve my issue! :) 
I returned with an update to my issue. When SMCROUTE correctly build Multicast routing from source host to Tunnel interface, and can't build Multicast routing on destination host from tunnel to some interface.

The main problem in my setup was, that Multicast traffic generated with iperf goes not only through Tunnel interface but also through physical underlying interface for tunnel (on which tunnel was build) due to the nature of iperf to bound on some ethernet interface by default. 
That's why on destination host Multicast traffic was duplicated for the same group and SMCROUTE didn't know how to build correctly multicast routing table. 

P/S: Is it possible to add some debugging functionality to notify users about such behavior?

**Comment by troglobit** [comment] 2019-05-12 07:30
@lubouski Great to hear you fixed your problem  There are unfortunately no easy way to add debug func. to SMCRoute since it only manipulates the kernel multicast routing table.

**Comment by troglobit** [comment] 2021-07-27 20:02
Minor update.  Although I have not tested this since the original report date, there have been other related reports; #142 and #161. They share the same root problem, which seems to be fixed in later kernels.   There is an auto test for issue #161, called `vlan.sh`, which sets up a shared base interface with VLAN interfaces on top.   I have not yet made a similar test for this GRE problem, but it might be worth mentioning in this thread that there at least is hope now.

https://github.com/troglobit/smcroute/actions/runs/1072472846

Check the link above to see OS details of the Azure runner.

**Comment by troglobit** [comment] 2021-08-12 20:41
I just added a multicast-over-GRE-tunnel test to the test suite.  I recommend anyone with questions to look there for guidance:

https://github.com/troglobit/smcroute/blob/master/test/gre.sh

I had the same initial problems I believe I was seeing also with pimd back in 2019, but I'm starting to think that these issues may have been caused by reverse path filtering, because as soon as I added routes back to the sender on the receiving router, the kernel allowed the traffic to proceed to the routing stage, and also notified SMCRoute with a proper NOCACHE upcall message on reception on the receiving side.

I see no remaining issues with SMCRoute, and this thread has already hosted multiple other questions as well, so I'm closing this one.  Please open a new issue should you find any new problems, or use the Discussions tab for questions.

**Closed by troglobit** 2021-08-12 20:41 UTC
Labels: help-wanted
