### ISSUE TITLE
Corrupted "time to expire" debug message

### ISSUE THREAD

**Issue by Malvineous** [troglobit/smcroute#171] opened 2021-11-12 08:49 UTC
Just FYI it looks like there might be a typo in one of the debug messages, I'm seeing random characters appear:
```
Fri Nov 12 18:17:21 2021 daemon.info smcroute[14871]: Cache timeout, flushing unused (*,G) routes!
Fri Nov 12 18:17:21 2021 daemon.debug smcroute[14871]: Checking (p?????w?O@,ff05:fdaa::1) on br-lan, time to expire: last 60127 max 60 now: 60187
Fri Nov 12 18:17:21 2021 daemon.debug smcroute[14871]:   -> Nope, still active, valid 96 vs last valid 36.
Fri Nov 12 18:17:21 2021 daemon.debug smcroute[14871]: Checking (p?????w?O@,ff08:1500::ca03) on br-lan, time to expire: last 60127 max 60 now: 60187
Fri Nov 12 18:17:21 2021 daemon.debug smcroute[14871]:   -> Nope, still active, valid 12978 vs last valid 4549.
Fri Nov 12 18:17:21 2021 daemon.debug smcroute[14871]: Checking (p?????w?O@,ff08:1500::ca04) on br-lan, time to expire: last 60127 max 60 now: 60187
Fri Nov 12 18:17:21 2021 daemon.debug smcroute[14871]:   -> Nope, still active, valid 24635 vs last valid 8663.
```

**Comment by troglobit** [comment] 2021-11-12 09:55
What version of SMCRoute are you using?

**Comment by Malvineous** [comment] 2021-11-12 10:14
Should be the latest release supplied by the OpenWRT project, but I don't have anything set up at the moment to try cross-compiling the git version:
```
$ smcrouted -v
SMCRoute v2.5.3
```
It's running on a MIPS CPU if that makes a difference, I think it's a 32-bit platform:
```
$ cat /proc/cpuinfo
system type		: MediaTek MT7620A ver:2 eco:6
machine			: Lenovo Y1
cpu model		: MIPS 24KEc V5.0
isa			: mips1 mips2 mips32r1 mips32r2
```

**Comment by troglobit** [comment] 2021-11-12 10:42
Thanks, that'll save time when attempting to reproduce.  Currently it looks like an uninitialized stack variable that should default to "*", so I'll probably release a fix this weekend.

**Comment by troglobit** [comment] 2021-11-12 17:20
Found it, wasn't uninitialized, it was too small for IPv6 addresses, fixed now.  Will be in the next release, likely v2.5.4

**Closed** 2021-11-12 17:19 UTC

**Comment by Malvineous** [comment] 2021-11-13 13:09
Interesting, thanks for the quick fix!
